MERGE INTO PLAYER (PLAYER_NAME, AGE, HEIGHT, RANKING) key(player_name) values ('Rafael Nadal', 32, 185, 1);
MERGE INTO PLAYER (PLAYER_NAME, AGE, HEIGHT, RANKING) key(player_name) values ('Roger Federer', 36, 185, 2);
MERGE INTO PLAYER (PLAYER_NAME, AGE, HEIGHT, RANKING) key(player_name) values ('Alexander Zverev', 21, 198, 3);
MERGE INTO PLAYER (PLAYER_NAME, AGE, HEIGHT, RANKING) key(player_name) values ('Juan Martin del Potro', 29, 198, 4);
MERGE INTO PLAYER (PLAYER_NAME, AGE, HEIGHT, RANKING) key(player_name) values ('Marin Cilic', 29, 198, 5);
MERGE INTO PLAYER (PLAYER_NAME, AGE, HEIGHT, RANKING) key(player_name) values ('Grigor Dimitrov', 27, 191, 6);
MERGE INTO PLAYER (PLAYER_NAME, AGE, HEIGHT, RANKING) key(player_name) values ('Dominic Thiem', 24, 185, 7);
MERGE INTO PLAYER (PLAYER_NAME, AGE, HEIGHT, RANKING) key(player_name) values ('Kevin Anderson', 32, 203, 8);
MERGE INTO PLAYER (PLAYER_NAME, AGE, HEIGHT, RANKING) key(player_name) values ('David Goffin', 27, 180, 9);
MERGE INTO PLAYER (PLAYER_NAME, AGE, HEIGHT, RANKING) key(player_name) values ('John Isner', 33, 208, 10);